# Generated by Django 4.1.3 on 2023-03-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currentSpeed', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('fuelCapacity', models.IntegerField()),
                ('timeForInspection', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aircrafts/')),
                ('availability', models.BooleanField()),
            ],
        ),
    ]
